root: ${cluster_env.path}
  
dst:
  CIFAR10:
    _target_: lscaleuq.dataset_uq.CIFAR10Dataset
    root:  ${join:${zs_datasets.root},CIFAR-10}
    train: False
    transform: ${transform.val}

  CIFAR100:
    _target_: lscaleuq.dataset_uq.CIFAR100Dataset
    root: ${join:${zs_datasets.root},CIFAR-100}
    train: False
    transform: ${transform.val}
