name: CC12M
path: data/CC12M
web_dataset: true
caption_dataset: true

train:
  _target_: lumen.dataset_uq.get_webdataset
  root: ${dataset.path}
  split: train
  transform: ${transform.train}
  length: 7849619
  batch_size: ${batch_size}

val:
  _target_: lumen.dataset_uq.get_webdataset
  root: ${dataset.path}
  split: val
  transform: ${transform.val}
  length: 19008
  batch_size: ${batch_size}