root: ${cluster_env.path}
  
dst:
  CIFAR10:
    _target_: lumen.dataset_uq.CIFAR10Dataset
    root:  ${join:${zs_datasets.root},CIFAR-10}
    train: False
    transform: ${transform.val}

  CIFAR100:
    _target_: lumen.dataset_uq.CIFAR100Dataset
    root: ${join:${zs_datasets.root},CIFAR-100}
    train: False
    transform: ${transform.val}
  
  Aircraft:
    _target_: lumen.dataset_uq.FGVCAircraftDataset
    root: ${join:${zs_datasets.root},dataset_suite}
    split: test
    transform: ${transform.val}
  
  Caltech101:
    _target_: lumen.dataset_uq.Caltech101Dataset
    root: ${join:${zs_datasets.root},dataset_suite,caltech101}
    split: test
    transform: ${transform.val}

  Cars:
    _target_: lumen.dataset_uq.StanfordCarsDataset
    root: ${join:${zs_datasets.root},dataset_suite,stanford_cars}
    split: test
    transform: ${transform.val}

  EuroSAT:
    _target_: lumen.dataset_uq.EuroSATDataset
    root: ${join:${zs_datasets.root},dataset_suite,EuroSAT_RGB}
    split: test
    transform: ${transform.val}

  Flowers:
    _target_: lumen.dataset_uq.Flowers102Dataset
    root: ${join:${zs_datasets.root},dataset_suite,flowers102}
    split: test
    transform: ${transform.val}

  Food:
    _target_: lumen.dataset_uq.Food101Dataset
    root: ${join:${zs_datasets.root},dataset_suite,food-101}
    split: test
    transform: ${transform.val}

  Pets:
    _target_: lumen.dataset_uq.OxfordPetsDataset
    root: ${join:${zs_datasets.root}, dataset_suite,oxford-iiit-pet}
    split: test
    transform: ${transform.val}

  Textures:
    _target_: lumen.dataset_uq.DTDDataset
    root: ${join:${zs_datasets.root},dataset_suite,dtddataset}
    split: test
    transform: ${transform.val}

  SUN:
    _target_: lumen.dataset_uq.SUN397Dataset
    root: ${join:${zs_datasets.root},dataset_suite,SUN397}
    split: test
    transform: ${transform.val}

  UCF:
    _target_: lumen.dataset_uq.UCF101Dataset
    root: ${join:${zs_datasets.root},dataset_suite,UCF-101-midframes}
    split: test
    transform: ${transform.val}
