name: ImageNet
path: /local/DEEPLEARNING/LargeScaleUQ/ImageNet
features_dataset: false
web_dataset: false
caption_dataset: false

train: 
  _target_: lumen.dataset_uq.ImageNetDataset
  root: ${dataset.path}
  split: train
  transform: ${transform.train}

val:
  _target_: lumen.dataset_uq.ImageNetDataset
  root: ${dataset.path}
  split: val
  transform: ${transform.val}
