CUDA_VISIBLE_DEVICES="1" python lscaleuq/run.py \
 wandbconf.name=ConfidNetVLMFAttn_ImageNetEmb_evalZS \
 datasets=ImageNetEmb \
 models=ConfidNetVLMAttention \
 models.model.layers=[512,256,128,1] \
 models.model.keep_frozen=True \
 backbone_model=CLIP_ViT_B32 \
 losses=BCE \
 losses.loss.weight=1.5 \
 optim=SGD \
 optim.optimizer.lr=0.001 \
 engine.n_epochs=100 \
 engine.batch_size=512 \
 engine.eval_only=False \
 engine.eval_freq=1 \
 engine.template=imagenet_base \