PYTHONWARNINGS="ignore" CUDA_VISIBLE_DEVICES="0" python lscaleuq/run.py \
 exp_name="predicted_text" \
 dataset=cc3m_emb \
 backbone=clip_vit_b32 \
 zs_datasets=data_suite+imgnet \
 model=confidnetvlm_attention \
 model.keep_frozen=true \
 model.n_iter_freeze_proj=1000 \
 model.use_predicted_caption=true \
 engine.n_epochs=350 \
 engine.batchwise_train=true \
 engine.eval_zs=true \
 engine.eval_only=false \
 resume=False \
 loss.weight=1.5 \
 optimizer.lr=0.001 \
 batch_size=512 \
 cluster_env=cnam \
 wandb_mode=online
