PYTHONWARNINGS="ignore" CUDA_VISIBLE_DEVICES="1" python lscaleuq/run.py \
 exp_name="transformer_u+t+v" \
 dataset=cc12m_emb \
 backbone=clip_vit_b32 \
 zs_datasets=data_suite+imgnet \
 model=confidnetvlm_trsf \
 model.n_layers=1 \
 model.n_heads=8 \
 model.use_predicted_caption=true \
 model.use_visual=true \
 engine.n_epochs=400 \
 engine.batchwise_train=true \
 engine.eval_zs=true \
 engine.eval_only=false \
 resume=False \
 loss.weight=1.5 \
 optimizer.lr=0.001 \
 batch_size=512 \
 cluster_env=cnam \
 wandb_mode=online

PYTHONWARNINGS="ignore" CUDA_VISIBLE_DEVICES="1" python lscaleuq/run.py \
 exp_name="transformer_u+t" \
 dataset=cc12m_emb \
 backbone=clip_vit_b32 \
 zs_datasets=data_suite+imgnet \
 model=confidnetvlm_trsf \
 model.n_layers=1 \
 model.n_heads=8 \
 model.use_predicted_caption=true \
 model.use_visual=false \
 engine.n_epochs=400 \
 engine.batchwise_train=true \
 engine.eval_zs=true \
 engine.eval_only=false \
 resume=False \
 loss.weight=1.5 \
 optimizer.lr=0.001 \
 batch_size=512 \
 cluster_env=cnam \
 wandb_mode=online

PYTHONWARNINGS="ignore" CUDA_VISIBLE_DEVICES="1" python lscaleuq/run.py \
 exp_name="transformer_u" \
 dataset=cc12m_emb \
 backbone=clip_vit_b32 \
 zs_datasets=data_suite+imgnet \
 model=confidnetvlm_trsf \
 model.n_layers=1 \
 model.n_heads=8 \
 model.use_predicted_caption=false \
 model.use_visual=false \
 engine.n_epochs=400 \
 engine.batchwise_train=true \
 engine.eval_zs=true \
 engine.eval_only=false \
 resume=False \
 loss.weight=1.5 \
 optimizer.lr=0.001 \
 batch_size=512 \
 cluster_env=cnam \
 wandb_mode=online
