CUDA_VISIBLE_DEVICES="1" python lscaleuq/run.py \
 exp_name=ConfidNetVLMFreezeAttention_ImageNetEmb \
 datasets=imagenet_emb \
 model=confidnetvlm_attention \
 model.layers=[512,256,128,1] \
 model.keep_frozen=True \
 backbone=clip_vit_b32 \
 loss=bce \
 loss.weight=1.5 \
 optimizer=sgd \
 optimizer.lr=0.001 \
 engine.n_epochs=100 \
 batch_size=512 \
 engine.eval_only=False \
 engine.eval_freq=1 \
 engine.template=base \