name: CC12M
path: ${join:${cluster_env.path},CC12M,cc12m}
features_dataset: false
web_dataset: true
caption_dataset: true

train:
  _target_: lscaleuq.dataset_uq.get_webdataset
  root: ${dataset.path}
  split: train
  transform: ${transform.train}
  length: 7849619
  batch_size: ${batch_size}

val:
  _target_: lscaleuq.dataset_uq.get_webdataset
  root: ${dataset.path}
  split: val
  transform: ${transform.val}
  length: 19008
  batch_size: ${batch_size}