name: LAIONEmb
path: /local/DEEPLEARNING/LargeScaleUQ/LAION/emb
features_dataset: true
web_dataset: false
caption_dataset: true

train:
  _target_: lscaleuq.dataset_uq.abstract_emb_dts.EmbDataset
  root: ${dataset.path}
  split: train

val:
  _target_: lscaleuq.dataset_uq.abstract_emb_dts.EmbDataset
  root: ${dataset.path}
  split: val