name: Pixmo
path: ${join:${cluster_env.path},Pixmo-cap}
features_dataset: false
web_dataset: false
caption_dataset: true

train: 
  _target_: lscaleuq.dataset_uq.PixMoDataset
  root: ${dataset.path}
  split: train
  transform: ${transform.train}

val:
  _target_: lscaleuq.dataset_uq.PixMoDataset
  root: ${dataset.path}
  split: val
  transform: ${transform.val}
