_target_: lscaleuq.models.ConfidNetVLMTrsf
visual_dim: ${backbone.vision_dim}
textual_dim: ${backbone.vision_dim}
layers: [512, 256, 128, 1]
activation: 'relu'
negative_slope: 0.01
use_sigmoid: ${if:${eq:${loss._target_},lscaleuq.losses.MSELoss},True,False}
n_layers: 1
n_heads: 8
use_predicted_caption: True
use_visual: True