_target_: lscaleuq.models.ConfidNet
visual_dim: ${backbone.vision_dim}
textual_dim: ${backbone.vision_dim}
layers: [512,512,512,1]
activation: 'leaky_relu'
negative_slope: 0.01
use_sigmoid: ${if:${eq:${loss.name},MSE},True,False}
