_target_: lscaleuq.models.ConfidNetVLMConv1d
visual_dim: ${backbone_model.vision_dim}
textual_dim: ${backbone_model.vision_dim}
layers: [512, 512, 512, 1]
activation: 'leaky_relu'
negative_slope: 0.01
use_sigmoid: ${if:${eq:${losses.name},MSE},True,False}
kernel_size: 3
use_activation: True
pooling_type: avg