_target_: lscaleuq.engine.trainer.Trainer
n_epochs: 10
print_freq: 200
max_iter_epoch: -1
use_gather: false
eval_freq: 5
eval_zs_freq: 5
save_freq: 5
eval_only: false
eval_zs: false
template_type: base
features_dataset: ${dataset.features_dataset}
web_dataset: ${dataset.web_dataset}
caption_dataset: ${dataset.caption_dataset}
resume: ${resume}
batchwise_train: false
display_progress: false
